version: '3.4'

services:
  auctiondb:
    image: mongo

  rabbimq:
    image: rabbitmq:3-management

  auction.products:
    image: ${DOCKER_REGISTRY-}auctionproducts
    build:
      context: .
      dockerfile: src/Services/Products/Auction.Products/Dockerfile

  auction.sourcing:
    image: ${DOCKER_REGISTRY-}auctionsourcing
    build:
      context: .
      dockerfile: Auction.Sourcing/Dockerfile

