version: '3.4'

services:
  auctiondb:
    container_name: auctiondb
    restart: always
    volumes:
       - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
       - "27017:27017"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
       - "5672:5672"
       - "15672:15672" 

  auction.products:
    container_name: auctionproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionString=mongodb://auctiondb:27017"
    depends_on:
        - auctiondb
    ports:
      - "8000:80" 
    volumes:
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets



  auction.sourcing:
    container_name: auctionsourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://auctiondb:27017"
      - "EventBus:HostName=rabbitmq"
    depends_on: 
      - auctiondb
      - rabbitmq
    ports:
      - "8001:80"
    volumes:
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
